# Generated by Django 5.0.7 on 2024-07-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='id',
        ),
        migrations.AlterField(
            model_name='navbar',
            name='titulo',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
